### ISSUE TITLE
Please release version to 1.31

### ISSUE THREAD

**Issue by ryrxq** [Xposed-Modules-Repo/eu.faircode.xlua#3]
Hi @JasonKhew96,

XPrivacyLua has released [version 1.31](https://github.com/M66B/XPrivacyLua/releases/tag/1.31). Please upgrade it. Thanks!

**Comment by JasonKhew96** [comment]
https://github.com/Xposed-Modules-Repo/eu.faircode.xlua/releases/tag/132-1.31
